after-login-command = []
after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

exec-on-workspace-change = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse monitor-lazy-center' 

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 16  # Giữ nguyên hoặc tùy ý
inner.vertical = 5
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]

alt-backslash = 'layout tiles horizontal vertical'
alt-equal = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-f = 'fullscreen'

shift-ctrl-h = 'move left'
shift-ctrl-j = 'move down'
shift-ctrl-k = 'move up'
shift-ctrl-l = 'move right'

alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'

alt-c = 'workspace C' # Coding & Terminal
alt-b = 'workspace B' # Browser
alt-w = 'workspace W' # Work/Comm (Slack, Discord, Meet,...)
alt-d = 'workspace D' # Notes/Docs (Thay thế cho N)
alt-p = 'workspace P' # Music/Media/Game/Misc (Thay thế cho M)
alt-s = 'workspace S' # Settings/System

shift-ctrl-c = 'move-node-to-workspace C'
shift-ctrl-b = 'move-node-to-workspace B'
shift-ctrl-w = 'move-node-to-workspace W'
shift-ctrl-d = 'move-node-to-workspace D' # Thay thế cho N
shift-ctrl-p = 'move-node-to-workspace P' # Thay thế cho M
shift-ctrl-s = 'move-node-to-workspace S'

alt-ctrl-tab = 'move-workspace-to-monitor --wrap-around next'

alt-ctrl-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] 
f = ['layout floating tiling', 'mode main'] 
backspace = ['close-all-windows-but-current', 'mode main']

alt-ctrl-h = ['join-with left', 'mode main']
alt-ctrl-j = ['join-with down', 'mode main']
alt-ctrl-k = ['join-with up', 'mode main']
alt-ctrl-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace C"

[[on-window-detected]]
if.app-id ='com.google.antigravity'
run = "move-node-to-workspace C"

[[on-window-detected]]
if.app-id ='com.raphaelamorim.rio'
run = "move-node-to-workspace C"

#Browser
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.microsoft.edgemac'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = "move-node-to-workspace B"

#Document
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace W"

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = "move-node-to-workspace D" # Thay thế cho N

[[on-window-detected]]
if.app-id = 'com.apple.iBooksX'
run = "move-node-to-workspace D" # Thay thế cho N

[[on-window-detected]]
if.app-id = 'info.sioyek.sioyek'
run = "move-node-to-workspace D" # Thay thế cho N
 
[[on-window-detected]]
if.app-id = 'notion.id'
run = "move-node-to-workspace D" # Thay thế cho N

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = "move-node-to-workspace D" # Thay thế cho N

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace D" # Thay thế cho N

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace C'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace W'

[[on-window-detected]]
if.app-id = 'com.blackmagic-design.DaVinciResolveLite'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.obsproject.obs-studio'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'com.vmware.fusion'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'org.qutebrowser.qutebrowser'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.window-title-regex-substring = 'zathura'
run = 'move-node-to-workspace D'

[[on-window-detected]]
if.app-id = 'com.riotgames.RiotGames.RiotClient'
run = ['move-node-to-workspace P']

#which work space is on which monitor
[workspace-to-monitor-force-assignment]
W = 1 
C = 'main'
B = 'main'
S = 'main'
D = 'secondary' # Thay thế cho N
P = 'secondary' # Thay thế cho M

#join 
# alt-ctrl-; for service mode
# alt-ctrl -> L or H,.... to merge ...
