#!/bin/bash
set -e # Dừng ngay nếu lỗi

# --- CẤU HÌNH MÀU SẮC ---
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== BẮT ĐẦU CÀI ĐẶT NIX-DARWIN (FINAL V2) ===${NC}"

# --- BƯỚC 1: DỌN DẸP BACKUP ---
echo -e "\n${BLUE}[Step 1] Kiểm tra file backup hệ thống...${NC}"
SYSTEM_FILES=("bashrc" "zshrc" "bash.bashrc" "synthetic.conf")
for file in "${SYSTEM_FILES[@]}"; do
    BACKUP_FILE="/etc/${file}.backup-before-nix"
    ORIGINAL_FILE="/etc/${file}"
    if [ -f "$BACKUP_FILE" ]; then
        echo "Khôi phục: $BACKUP_FILE -> $ORIGINAL_FILE"
        sudo mv "$BACKUP_FILE" "$ORIGINAL_FILE"
    fi
done

# --- BƯỚC 2: CÀI ĐẶT NIX ---
if ! command -v nix &> /dev/null; then
    echo -e "\n${BLUE}[Step 2] Đang cài đặt Nix...${NC}"
    sh <(curl -L https://nixos.org/nix/install) --daemon --yes
    echo -e "${GREEN}Nix đã được cài đặt!${NC}"
else
    echo -e "\n${BLUE}[Step 2] Nix đã có sẵn.${NC}"
fi

# --- BƯỚC 3: CẤU HÌNH HỆ THỐNG /etc/nix/nix.conf ---
echo -e "\n${BLUE}[Step 3] Cấu hình Nix Daemon (Fix SSL & Quyền)...${NC}"

# 1. Tạo thư mục config
if [ ! -d "/etc/nix" ]; then sudo mkdir -p /etc/nix; fi

# 2. GHI CẤU HÌNH CHUẨN (Fix SSL, Trusted User, Flakes)
echo "Đang cập nhật /etc/nix/nix.conf..."
sudo bash -c "cat > /etc/nix/nix.conf <<EOF
# Generated by install.sh
build-users-group = nixbld
trusted-users = root $USER
ssl-cert-file = /etc/ssl/cert.pem
experimental-features = nix-command flakes
EOF"

# 3. Restart Daemon
echo "Khởi động lại Nix Daemon..."
if [ -f "/Library/LaunchDaemons/org.nixos.nix-daemon.plist" ]; then
    sudo launchctl kickstart -k system/org.nixos.nix-daemon 2>/dev/null || echo "Daemon restarting..."
    sleep 3
fi

# --- BƯỚC 4: CẤU HÌNH USER ---
mkdir -p ~/.config/nix
echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

# --- BƯỚC 5: BUILD & ACTIVATE (DÙNG SUDO) ---
echo -e "\n${BLUE}[Step 5] Bắt đầu Build & Activate nix-darwin...${NC}"

# Nạp môi trường Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# Set biến cho phép gói unfree
export NIXPKGS_ALLOW_UNFREE=1

# === THAY ĐỔI QUAN TRỌNG Ở ĐÂY ===
# Chúng ta dùng 'sudo' trực tiếp cho lệnh nix run để kích hoạt hệ thống.
# Dùng cờ --preserve-env (-E) để giữ lại biến NIXPKGS_ALLOW_UNFREE khi sudo
echo "${YELLOW}Đang chạy kích hoạt hệ thống với quyền Root...${NC}"

sudo -E nix run \
    --extra-experimental-features 'nix-command flakes' \
    nix-darwin -- switch --flake . --impure

echo -e "\n${GREEN}===============================================${NC}"
echo -e "${GREEN}   CÀI ĐẶT HOÀN TẤT! CHÚC MỪNG BẠN!          ${NC}"
echo -e "${GREEN}===============================================${NC}"
echo "Vui lòng tắt Terminal và mở lại."
