# Sesh configuration file
# For more info see: https://github.com/joshmedeski/sesh

[[session]]
name = "Nix Config ⚡️"
path = "~/nix-config"
startup_command = "nvim"

[[session]]
name = "docs-launcher"
startup_command = '''
tmuxinator start default documents document-api document-admin
tmux kill-session -t docs-launcher
'''
# tmuxinator start documents documents document-api document-admin
#                  ^template  ^arg[0]   ^arg[1]     ^arg[2]

# Import paths from other tools
[zoxide]
enable = true

[tmux]
enable = true
