function nix-dev-rm -d "Remove devenv configuration and clean up Git exclude"
    # Prompt for confirmation to avoid accidental deletion
    read -P "⚠️  Are you sure you want to remove all devenv configurations in this project? [y/N] " confirm
    if test "$confirm" != "y" -a "$confirm" != "Y"
        echo "⏭️  Operation cancelled."
        return 0
    end

    # 1. Deny direnv FIRST while .envrc still exists
    if type -q direnv
        if test -f .envrc
            direnv deny
            echo "✅ Executed 'direnv deny' to revoke environment access."
        end
    end

    # 2. Remove files and directories generated by devenv
    echo "🗑️  Removing devenv files (.envrc, devenv.nix, devenv.yaml, .devenv/)..."
    rm -rf .envrc devenv.nix devenv.yaml .devenv/

    # 3. Clean up .git/info/exclude if it exists
    set -l exclude_file ".git/info/exclude"
    if test -f $exclude_file
        # Use grep to filter out our devenv lines and write to a temporary file,
        # then replace the original file.
        grep -vE "^(\.envrc|devenv\.nix|devenv\.yaml|\.devenv/)\$" $exclude_file > "$exclude_file.tmp"
        mv "$exclude_file.tmp" $exclude_file
        echo "🧹 Cleaned up $exclude_file (Removed devenv entries)."
    end

    echo "💥 Cleanup complete! Devenv is completely removed from this project."
end