# Status
set -g status-interval 1
set -g escape-time 10
set -g repeat-time 500
set -g display-time 1500

#image for markdown
set -g allow-passthrough on

# draw image for markdown in nvim
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# Terminal colors
set -g default-terminal "tmux-256color"
set -sag terminal-features ",*:RGB"
set -sag terminal-features ",*:usstyle"

# Enable CSI u
# enabling this will break copy paste in Kitty terminal
# set -g extended-keys on
# set -sag terminal-features 'xterm*:extkeys'


set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind-key -T copy-mode-vi Escape send-keys -X cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Rebind forward search to Ctrl + f (example)
bind-key -T copy-mode-vi 'C-f' command-prompt -p "Search forward:" "send -X search-forward \"%%\""

# Enable focus events
set -g focus-events on

# Enable gapeless window
set -g renumber-windows on

# Make index start from 1
set -g base-index 1
setw -g pane-base-index 1

# Do not detach when destroying a session
set -g detach-on-destroy off

# Change prefix key
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Kill pane
bind x kill-pane

# Panes
# Change dimension
unbind Left
unbind Right
unbind Up
unbind Down

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5

# Move each other panel 
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Toggle fullsize pane
bind -r m resize-pane -Z

# Slpit panel
unbind %
bind '\' split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

bind j choose-tree -F "#{E:@custom_choose_tree_format}" -Z "join-pane -h -s "%%""
bind J choose-tree -F "#{E:@custom_choose_tree_format}" -Z "join-pane -v -s "%%""
bind b if-shell " [ #{window_panes} -gt '1' ] " { break-pane -a }

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# reload config file
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'

# tmux-resurrect settings
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum settings
set -g @continuum-restore 'on'

# Configure Catppuccin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none" # none == default
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"
 
# status left look and feel
set -g status-left-length 80
set -g status-left ""

# status right look and feel
set -g status-right-length 160
set -g status-right ""

# custom var
set -g @custom_separator "#[fg=#{@thm_overlay_0},none]|"

# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


set -sg terminal-overrides ",*:RGB"
# Theme: borders
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# Theme: status
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right ""

# Theme: status (windows)
set -g status-justify centre
set -g window-status-format "#[fg=grey] ● "
set -g window-status-current-format "#[fg=yellow] ● "
set -g window-status-bell-style "fg=red,nobold"


# Transparent Background
set -g status-bg default
set -g status-style bg=default
